language: python
python:
  - 3.7
before_install:
  - pip install -U pip
install:
  - pip install ".[test]" . # install package + test dependencies
script: nosetests --with-coverage # run tests
deploy:
  provider: pypi
  user: __token__
  password:
    secure: eTILzoBcl0deRq5YlpyYqWQ7OEFE15ES3vN+tSAZIIkgCYE3xuBA6GXRrjcuskkZia3PMdvAUOo/hNeQzQHs5PFG5iNr5SsZC3zPohfReHziS+HI7zJR9UErazmYKeyeomm152wlQwmLIQ7W3LfUuJNol1HrVBYiy5myU2IHPnFgKiK33I29dIVjQlDzIBysRj1koIzumCC20BXm9z41Fh2Y6SNsSoc/LoS3OBSbclnM6szcs9nL0yHuNAE/zMLj5gibogl2ElTPeqowZ6dJEmF+Qz1YrUzzlCqtfg7QfsBwZ3rKb906ipBUoCgPWwBgPyE+m61xgpHrPISdWSxCSlZ4qPnfJQ8EGipRiGF2khaAegIkx6Ief4Lqr3VwvoJXWqL205xruzkk9F1Q21mTZw+D/9VQwrfGzIrmtb08OX+ZUVaXn+u2PVJgfQkhN1LWscFl2+3eo96iUN3JKqVz1QFz/BW9j9KGA+DnY+qXwqVgJHFzUe29nAnd36oNQLlKbutGjkm525Fct0OteDbu7kSwNSClzc0Wy7R3G06rphUxpb4kpNTz/blFgj7PF5NqFvvlMeoSx9hqakCjqSMSmCMcuoNEUURoj6nvTK+J0gY7eo8fUVV5XzX+zkTwvjUZdFXc/w8I4WhS7T4ANnWmndG4kO/6HXc/eMR1BpK6dLM=
after_success:
  - codecov