language: python
python:
  - 3.7
before_install:
  - pip install -U pip
install:
  - pip install ".[test]" . # install package + test dependencies
script: nosetests --with-coverage --cover-package=pyapiconsoleir # run tests
deploy:
  provider: pypi
  user: __token__
  password:
    secure: 5AMReMem5h8EIgeRhJWFLsiZn2RdVL1bTTiiTutRbTQqvWuZhvwJbOl26XMee0QEn+6lNCQl3NSquK6SRQi3ATvzaE9nEBS76lH+dHMjU3SrNNeWdj5NcLXsHWC4CcLr8/SYMZBEyoG93ko9/+1xFDiWLT9TuDPUl75SCPYhoDVtYcqXorLwONRHbIdahB4p54DT31XEYpmE22CTo3zp32ZSfiY6nYSIOGR6T7qnX70dj6BjxdlntBml+V16jBCJDYWgReCIsoqfLnzp63B3FXApC66DRabVZCeOGj0vLBeyLYoU3wfCePfuE6zR1A4VStRWYgtLzRPCv7AlXN9o8L9wAueKqp9cvbHxaQBvXu9VxWU8nBNWu8Q0UZmZSCMVvqe0luNock03Ajeb2KMIfirVJX/idDDlIGJ/cLU5cZbmze03Jc8ItwQN2d4/UerU0c4jZ/OLXmIt+Sz9CiijIcYzI+udr0aYM0erFVLrDQxLadVVcNq99NGEpA9mbYxE4M13N5j9r7sq8PIKdrANI2hJhGBcMIi3ajvalXrbuwPyLZxt08bqorVATRDE4ub62Ap6w2J/XLXHNv31lPwzZK/mz2ThuO+zxctroukrjbOM4eymPBZNGt1w/2ejyHEcrp9FBry6A/rs4xCiNFvofucbeSdvhMwYvFWSIOQevMk=
after_success:
  - codecov